; M5Stack CoreS3 Port A peripheral checker
[env:m5stack-cores3]
platform = espressif32@6.7.0
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
lib_deps =
  m5stack/M5Unified
  sparkfun/SparkFun VL53L5CX Arduino Library
